#ifndef COPYWRITE_COLORS_DEFS_HPP
#define COPYWRITE_COLORS_DEFS_HPP

/*
 * Case-sensitive color names
 */

#define COLOR_ALICEBLUE            "aliceblue"
#define COLOR_ANTIQUEWHITE         "antiquewhite"
#define COLOR_AQUA                 "aqua"
#define COLOR_AQUAMARINE           "aquamarine"
#define COLOR_AZURE                "azure"
#define COLOR_BEIGE                "beige"
#define COLOR_BISQUE               "bisque"
#define COLOR_BLACK                "black"
#define COLOR_BLANCHEDALMOND       "blanchedalmond"
#define COLOR_BLUE                 "blue"
#define COLOR_BLUEVIOLET           "blueviolet"
#define COLOR_BROWN                "brown"
#define COLOR_BURLYWOOD            "burlywood"
#define COLOR_CADETBLUE            "cadetblue"
#define COLOR_CHARTREUSE           "chartreuse"
#define COLOR_CHOCOLATE            "chocolate"
#define COLOR_CORAL                "coral"
#define COLOR_CORNFLOWERBLUE       "cornflowerblue"
#define COLOR_CORNSILK             "cornsilk"
#define COLOR_CRIMSON              "crimson"
#define COLOR_CYAN                 "cyan"
#define COLOR_DARKBLUE             "darkblue"
#define COLOR_DARKCYAN             "darkcyan"
#define COLOR_DARKGOLDENROD        "darkgoldenrod"
#define COLOR_DARKGRAY             "darkgray"
#define COLOR_DARKGREY             "darkgrey"
#define COLOR_DARKGREEN            "darkgreen"
#define COLOR_DARKKHAKI            "darkkhaki"
#define COLOR_DARKMAGENTA          "darkmagenta"
#define COLOR_DARKOLIVEGREEN       "darkolivegreen"
#define COLOR_DARKORANGE           "darkorange"
#define COLOR_DARKORCHID           "darkorchid"
#define COLOR_DARKRED              "darkred"
#define COLOR_DARKSALMON           "darksalmon"
#define COLOR_DARKSEAGREEN         "darkseagreen"
#define COLOR_DARKSLATEBLUE        "darkslateblue"
#define COLOR_DARKSLATEGRAY        "darkslategray"
#define COLOR_DARKSLATEGREY        "darkslategrey"
#define COLOR_DARKTURQUOISE        "darkturquoise"
#define COLOR_DARKVIOLET           "darkviolet"
#define COLOR_DEEPPINK             "deeppink"
#define COLOR_DEEPSKYBLUE          "deepskyblue"
#define COLOR_DIMGRAY              "dimgray"
#define COLOR_DIMGREY              "dimgrey"
#define COLOR_DODGERBLUE           "dodgerblue"
#define COLOR_FIREBRICK            "firebrick"
#define COLOR_FLORALWHITE          "floralwhite"
#define COLOR_FORESTGREEN          "forestgreen"
#define COLOR_FUCHSIA              "fuchsia"
#define COLOR_GAINSBORO            "gainsboro"
#define COLOR_GHOSTWHITE           "ghostwhite"
#define COLOR_GOLD                 "gold"
#define COLOR_GOLDENROD            "goldenrod"
#define COLOR_GRAY                 "gray"
#define COLOR_GREY                 "grey"
#define COLOR_GREEN                "green"
#define COLOR_GREENYELLOW          "greenyellow"
#define COLOR_HONEYDEW             "honeydew"
#define COLOR_HOTPINK              "hotpink"
#define COLOR_INDIANRED            "indianred"
#define COLOR_INDIGO               "indigo"
#define COLOR_IVORY                "ivory"
#define COLOR_KHAKI                "khaki"
#define COLOR_LAVENDER             "lavender"
#define COLOR_LAVENDERBLUSH        "lavenderblush"
#define COLOR_LAWNGREEN            "lawngreen"
#define COLOR_LEMONCHIFFON         "lemonchiffon"
#define COLOR_LIGHTBLUE            "lightblue"
#define COLOR_LIGHTCORAL           "lightcoral"
#define COLOR_LIGHTCYAN            "lightcyan"
#define COLOR_LIGHTGOLDENRODYELLOW "lightgoldenrodyellow"
#define COLOR_LIGHTGRAY            "lightgray"
#define COLOR_LIGHTGREY            "lightgrey"
#define COLOR_LIGHTGREEN           "lightgreen"
#define COLOR_LIGHTPINK            "lightpink"
#define COLOR_LIGHTSALMON          "lightsalmon"
#define COLOR_LIGHTSEAGREEN        "lightseagreen"
#define COLOR_LIGHTSKYBLUE         "lightskyblue"
#define COLOR_LIGHTSLATEGRAY       "lightslategray"
#define COLOR_LIGHTSLATEGREY       "lightslategrey"
#define COLOR_LIGHTSTEELBLUE       "lightsteelblue"
#define COLOR_LIGHTYELLOW          "lightyellow"
#define COLOR_LIME                 "lime"
#define COLOR_LIMEGREEN            "limegreen"
#define COLOR_LINEN                "linen"
#define COLOR_MAGENTA              "magenta"
#define COLOR_MAROON               "maroon"
#define COLOR_MEDIUMAQUAMARINE     "mediumaquamarine"
#define COLOR_MEDIUMBLUE           "mediumblue"
#define COLOR_MEDIUMORCHID         "mediumorchid"
#define COLOR_MEDIUMPURPLE         "mediumpurple"
#define COLOR_MEDIUMSEAGREEN       "mediumseagreen"
#define COLOR_MEDIUMSLATEBLUE      "mediumslateblue"
#define COLOR_MEDIUMSPRINGGREEN    "mediumspringgreen"
#define COLOR_MEDIUMTURQUOISE      "mediumturquoise"
#define COLOR_MEDIUMVIOLETRED      "mediumvioletred"
#define COLOR_MIDNIGHTBLUE         "midnightblue"
#define COLOR_MINTCREAM            "mintcream"
#define COLOR_MISTYROSE            "mistyrose"
#define COLOR_MOCCASIN             "moccasin"
#define COLOR_NAVAJOWHITE          "navajowhite"
#define COLOR_NAVY                 "navy"
#define COLOR_OLDLACE              "oldlace"
#define COLOR_OLIVE                "olive"
#define COLOR_OLIVEDRAB            "olivedrab"
#define COLOR_ORANGE               "orange"
#define COLOR_ORANGERED            "orangered"
#define COLOR_ORCHID               "orchid"
#define COLOR_PALEGOLDENROD        "palegoldenrod"
#define COLOR_PALEGREEN            "palegreen"
#define COLOR_PALETURQUOISE        "paleturquoise"
#define COLOR_PALEVIOLETRED        "palevioletred"
#define COLOR_PAPAYAWHIP           "papayawhip"
#define COLOR_PEACHPUFF            "peachpuff"
#define COLOR_PERU                 "peru"
#define COLOR_PINK                 "pink"
#define COLOR_PLUM                 "plum"
#define COLOR_POWDERBLUE           "powderblue"
#define COLOR_PURPLE               "purple"
#define COLOR_REBECCAPURPLE        "rebeccapurple"
#define COLOR_RED                  "red"
#define COLOR_ROSYBROWN            "rosybrown"
#define COLOR_ROYALBLUE            "royalblue"
#define COLOR_SADDLEBROWN          "saddlebrown"
#define COLOR_SALMON               "salmon"
#define COLOR_SANDYBROWN           "sandybrown"
#define COLOR_SEAGREEN             "seagreen"
#define COLOR_SEASHELL             "seashell"
#define COLOR_SIENNA               "sienna"
#define COLOR_SILVER               "silver"
#define COLOR_SKYBLUE              "skyblue"
#define COLOR_SLATEBLUE            "slateblue"
#define COLOR_SLATEGRAY            "slategray"
#define COLOR_SLATEGREY            "slategrey"
#define COLOR_SNOW                 "snow"
#define COLOR_SPRINGGREEN          "springgreen"
#define COLOR_STEELBLUE            "steelblue"
#define COLOR_TAN                  "tan"
#define COLOR_TEAL                 "teal"
#define COLOR_THISTLE              "thistle"
#define COLOR_TOMATO               "tomato"
#define COLOR_TURQUOISE            "turquoise"
#define COLOR_VIOLET               "violet"
#define COLOR_WHEAT                "wheat"
#define COLOR_WHITE                "white"
#define COLOR_WHITESMOKE           "whitesmoke"
#define COLOR_YELLOW               "yellow"
#define COLOR_YELLOWGREEN          "yellowgreen"

/*
 * Case-insensitive color names
 */

#define ICOLOR_ALICEBLUE            "AliceBlue"
#define ICOLOR_ANTIQUEWHITE         "AntiqueWhite"
#define ICOLOR_AQUA                 "Aqua"
#define ICOLOR_AQUAMARINE           "Aquamarine"
#define ICOLOR_AZURE                "Azure"
#define ICOLOR_BEIGE                "Beige"
#define ICOLOR_BISQUE               "Bisque"
#define ICOLOR_BLACK                "Black"
#define ICOLOR_BLANCHEDALMOND       "BlanchedAlmond"
#define ICOLOR_BLUE                 "Blue"
#define ICOLOR_BLUEVIOLET           "BlueViolet"
#define ICOLOR_BROWN                "Brown"
#define ICOLOR_BURLYWOOD            "BurlyWood"
#define ICOLOR_CADETBLUE            "CadetBlue"
#define ICOLOR_CHARTREUSE           "Chartreuse"
#define ICOLOR_CHOCOLATE            "Chocolate"
#define ICOLOR_CORAL                "Coral"
#define ICOLOR_CORNFLOWERBLUE       "CornflowerBlue"
#define ICOLOR_CORNSILK             "Cornsilk"
#define ICOLOR_CRIMSON              "Crimson"
#define ICOLOR_CYAN                 "Cyan"
#define ICOLOR_DARKBLUE             "DarkBlue"
#define ICOLOR_DARKCYAN             "DarkCyan"
#define ICOLOR_DARKGOLDENROD        "DarkGoldenRod"
#define ICOLOR_DARKGRAY             "DarkGray"
#define ICOLOR_DARKGREY             "DarkGrey"
#define ICOLOR_DARKGREEN            "DarkGreen"
#define ICOLOR_DARKKHAKI            "DarkKhaki"
#define ICOLOR_DARKMAGENTA          "DarkMagenta"
#define ICOLOR_DARKOLIVEGREEN       "DarkOliveGreen"
#define ICOLOR_DARKORANGE           "DarkOrange"
#define ICOLOR_DARKORCHID           "DarkOrchid"
#define ICOLOR_DARKRED              "DarkRed"
#define ICOLOR_DARKSALMON           "DarkSalmon"
#define ICOLOR_DARKSEAGREEN         "DarkSeaGreen"
#define ICOLOR_DARKSLATEBLUE        "DarkSlateBlue"
#define ICOLOR_DARKSLATEGRAY        "DarkSlateGray"
#define ICOLOR_DARKSLATEGREY        "DarkSlateGrey"
#define ICOLOR_DARKTURQUOISE        "DarkTurquoise"
#define ICOLOR_DARKVIOLET           "DarkViolet"
#define ICOLOR_DEEPPINK             "DeepPink"
#define ICOLOR_DEEPSKYBLUE          "DeepSkyBlue"
#define ICOLOR_DIMGRAY              "DimGray"
#define ICOLOR_DIMGREY              "DimGrey"
#define ICOLOR_DODGERBLUE           "DodgerBlue"
#define ICOLOR_FIREBRICK            "FireBrick"
#define ICOLOR_FLORALWHITE          "FloralWhite"
#define ICOLOR_FORESTGREEN          "ForestGreen"
#define ICOLOR_FUCHSIA              "Fuchsia"
#define ICOLOR_GAINSBORO            "Gainsboro"
#define ICOLOR_GHOSTWHITE           "GhostWhite"
#define ICOLOR_GOLD                 "Gold"
#define ICOLOR_GOLDENROD            "GoldenRod"
#define ICOLOR_GRAY                 "Gray"
#define ICOLOR_GREY                 "Grey"
#define ICOLOR_GREEN                "Green"
#define ICOLOR_GREENYELLOW          "GreenYellow"
#define ICOLOR_HONEYDEW             "HoneyDew"
#define ICOLOR_HOTPINK              "HotPink"
#define ICOLOR_INDIANRED            "IndianRed"
#define ICOLOR_INDIGO               "Indigo"
#define ICOLOR_IVORY                "Ivory"
#define ICOLOR_KHAKI                "Khaki"
#define ICOLOR_LAVENDER             "Lavender"
#define ICOLOR_LAVENDERBLUSH        "LavenderBlush"
#define ICOLOR_LAWNGREEN            "LawnGreen"
#define ICOLOR_LEMONCHIFFON         "LemonChiffon"
#define ICOLOR_LIGHTBLUE            "LightBlue"
#define ICOLOR_LIGHTCORAL           "LightCoral"
#define ICOLOR_LIGHTCYAN            "LightCyan"
#define ICOLOR_LIGHTGOLDENRODYELLOW "LightGoldenRodYellow"
#define ICOLOR_LIGHTGRAY            "LightGray"
#define ICOLOR_LIGHTGREY            "LightGrey"
#define ICOLOR_LIGHTGREEN           "LightGreen"
#define ICOLOR_LIGHTPINK            "LightPink"
#define ICOLOR_LIGHTSALMON          "LightSalmon"
#define ICOLOR_LIGHTSEAGREEN        "LightSeaGreen"
#define ICOLOR_LIGHTSKYBLUE         "LightSkyBlue"
#define ICOLOR_LIGHTSLATEGRAY       "LightSlateGray"
#define ICOLOR_LIGHTSLATEGREY       "LightSlateGrey"
#define ICOLOR_LIGHTSTEELBLUE       "LightSteelBlue"
#define ICOLOR_LIGHTYELLOW          "LightYellow"
#define ICOLOR_LIME                 "Lime"
#define ICOLOR_LIMEGREEN            "LimeGreen"
#define ICOLOR_LINEN                "Linen"
#define ICOLOR_MAGENTA              "Magenta"
#define ICOLOR_MAROON               "Maroon"
#define ICOLOR_MEDIUMAQUAMARINE     "MediumAquaMarine"
#define ICOLOR_MEDIUMBLUE           "MediumBlue"
#define ICOLOR_MEDIUMORCHID         "MediumOrchid"
#define ICOLOR_MEDIUMPURPLE         "MediumPurple"
#define ICOLOR_MEDIUMSEAGREEN       "MediumSeaGreen"
#define ICOLOR_MEDIUMSLATEBLUE      "MediumSlateBlue"
#define ICOLOR_MEDIUMSPRINGGREEN    "MediumSpringGreen"
#define ICOLOR_MEDIUMTURQUOISE      "MediumTurquoise"
#define ICOLOR_MEDIUMVIOLETRED      "MediumVioletRed"
#define ICOLOR_MIDNIGHTBLUE         "MidnightBlue"
#define ICOLOR_MINTCREAM            "MintCream"
#define ICOLOR_MISTYROSE            "MistyRose"
#define ICOLOR_MOCCASIN             "Moccasin"
#define ICOLOR_NAVAJOWHITE          "NavajoWhite"
#define ICOLOR_NAVY                 "Navy"
#define ICOLOR_OLDLACE              "OldLace"
#define ICOLOR_OLIVE                "Olive"
#define ICOLOR_OLIVEDRAB            "OliveDrab"
#define ICOLOR_ORANGE               "Orange"
#define ICOLOR_ORANGERED            "OrangeRed"
#define ICOLOR_ORCHID               "Orchid"
#define ICOLOR_PALEGOLDENROD        "PaleGoldenRod"
#define ICOLOR_PALEGREEN            "PaleGreen"
#define ICOLOR_PALETURQUOISE        "PaleTurquoise"
#define ICOLOR_PALEVIOLETRED        "PaleVioletRed"
#define ICOLOR_PAPAYAWHIP           "PapayaWhip"
#define ICOLOR_PEACHPUFF            "PeachPuff"
#define ICOLOR_PERU                 "Peru"
#define ICOLOR_PINK                 "Pink"
#define ICOLOR_PLUM                 "Plum"
#define ICOLOR_POWDERBLUE           "PowderBlue"
#define ICOLOR_PURPLE               "Purple"
#define ICOLOR_REBECCAPURPLE        "RebeccaPurple"
#define ICOLOR_RED                  "Red"
#define ICOLOR_ROSYBROWN            "RosyBrown"
#define ICOLOR_ROYALBLUE            "RoyalBlue"
#define ICOLOR_SADDLEBROWN          "SaddleBrown"
#define ICOLOR_SALMON               "Salmon"
#define ICOLOR_SANDYBROWN           "SandyBrown"
#define ICOLOR_SEAGREEN             "SeaGreen"
#define ICOLOR_SEASHELL             "SeaShell"
#define ICOLOR_SIENNA               "Sienna"
#define ICOLOR_SILVER               "Silver"
#define ICOLOR_SKYBLUE              "SkyBlue"
#define ICOLOR_SLATEBLUE            "SlateBlue"
#define ICOLOR_SLATEGRAY            "SlateGray"
#define ICOLOR_SLATEGREY            "SlateGrey"
#define ICOLOR_SNOW                 "Snow"
#define ICOLOR_SPRINGGREEN          "SpringGreen"
#define ICOLOR_STEELBLUE            "SteelBlue"
#define ICOLOR_TAN                  "Tan"
#define ICOLOR_TEAL                 "Teal"
#define ICOLOR_THISTLE              "Thistle"
#define ICOLOR_TOMATO               "Tomato"
#define ICOLOR_TURQUOISE            "Turquoise"
#define ICOLOR_VIOLET               "Violet"
#define ICOLOR_WHEAT                "Wheat"
#define ICOLOR_WHITE                "White"
#define ICOLOR_WHITESMOKE           "WhiteSmoke"
#define ICOLOR_YELLOW               "Yellow"
#define ICOLOR_YELLOWGREEN          "YellowGreen"

/*
 * Color name HEX values
 */

#define COLORHEX_ALICEBLUE            0xf0f8ff00u
#define COLORHEX_ANTIQUEWHITE         0xfaebd700u
#define COLORHEX_AQUA                 0x00ffff00u
#define COLORHEX_AQUAMARINE           0x7fffd400u
#define COLORHEX_AZURE                0xf0ffff00u
#define COLORHEX_BEIGE                0xf5f5dc00u
#define COLORHEX_BISQUE               0xffe4c400u
#define COLORHEX_BLACK                0x00000000u
#define COLORHEX_BLANCHEDALMOND       0xffebcd00u
#define COLORHEX_BLUE                 0x0000ff00u
#define COLORHEX_BLUEVIOLET           0x8a2be200u
#define COLORHEX_BROWN                0xa52a2a00u
#define COLORHEX_BURLYWOOD            0xdeb88700u
#define COLORHEX_CADETBLUE            0x5f9ea000u
#define COLORHEX_CHARTREUSE           0x7fff0000u
#define COLORHEX_CHOCOLATE            0xd2691e00u
#define COLORHEX_CORAL                0xff7f5000u
#define COLORHEX_CORNFLOWERBLUE       0x6495ed00u
#define COLORHEX_CORNSILK             0xfff8dc00u
#define COLORHEX_CRIMSON              0xdc143c00u
#define COLORHEX_CYAN                 0x00ffff00u
#define COLORHEX_DARKBLUE             0x00008b00u
#define COLORHEX_DARKCYAN             0x008b8b00u
#define COLORHEX_DARKGOLDENROD        0xb8860b00u
#define COLORHEX_DARKGRAY             0xa9a9a900u
#define COLORHEX_DARKGREY             0xa9a9a900u
#define COLORHEX_DARKGREEN            0x00640000u
#define COLORHEX_DARKKHAKI            0xbdb76b00u
#define COLORHEX_DARKMAGENTA          0x8b008b00u
#define COLORHEX_DARKOLIVEGREEN       0x556b2f00u
#define COLORHEX_DARKORANGE           0xff8c0000u
#define COLORHEX_DARKORCHID           0x9932cc00u
#define COLORHEX_DARKRED              0x8b000000u
#define COLORHEX_DARKSALMON           0xe9967a00u
#define COLORHEX_DARKSEAGREEN         0x8fbc8f00u
#define COLORHEX_DARKSLATEBLUE        0x483d8b00u
#define COLORHEX_DARKSLATEGRAY        0x2f4f4f00u
#define COLORHEX_DARKSLATEGREY        0x2f4f4f00u
#define COLORHEX_DARKTURQUOISE        0x00ced100u
#define COLORHEX_DARKVIOLET           0x9400d300u
#define COLORHEX_DEEPPINK             0xff149300u
#define COLORHEX_DEEPSKYBLUE          0x00bfff00u
#define COLORHEX_DIMGRAY              0x69696900u
#define COLORHEX_DIMGREY              0x69696900u
#define COLORHEX_DODGERBLUE           0x1e90ff00u
#define COLORHEX_FIREBRICK            0xb2222200u
#define COLORHEX_FLORALWHITE          0xfffaf000u
#define COLORHEX_FORESTGREEN          0x228b2200u
#define COLORHEX_FUCHSIA              0xff00ff00u
#define COLORHEX_GAINSBORO            0xdcdcdc00u
#define COLORHEX_GHOSTWHITE           0xf8f8ff00u
#define COLORHEX_GOLD                 0xffd70000u
#define COLORHEX_GOLDENROD            0xdaa52000u
#define COLORHEX_GRAY                 0x80808000u
#define COLORHEX_GREY                 0x80808000u
#define COLORHEX_GREEN                0x00800000u
#define COLORHEX_GREENYELLOW          0xadff2f00u
#define COLORHEX_HONEYDEW             0xf0fff000u
#define COLORHEX_HOTPINK              0xff69b400u
#define COLORHEX_INDIANRED            0xcd5c5c00u
#define COLORHEX_INDIGO               0x4b008200u
#define COLORHEX_IVORY                0xfffff000u
#define COLORHEX_KHAKI                0xf0e68c00u
#define COLORHEX_LAVENDER             0xe6e6fa00u
#define COLORHEX_LAVENDERBLUSH        0xfff0f500u
#define COLORHEX_LAWNGREEN            0x7cfc0000u
#define COLORHEX_LEMONCHIFFON         0xfffacd00u
#define COLORHEX_LIGHTBLUE            0xadd8e600u
#define COLORHEX_LIGHTCORAL           0xf0808000u
#define COLORHEX_LIGHTCYAN            0xe0ffff00u
#define COLORHEX_LIGHTGOLDENRODYELLOW 0xfafad200u
#define COLORHEX_LIGHTGRAY            0xd3d3d300u
#define COLORHEX_LIGHTGREY            0xd3d3d300u
#define COLORHEX_LIGHTGREEN           0x90ee9000u
#define COLORHEX_LIGHTPINK            0xffb6c100u
#define COLORHEX_LIGHTSALMON          0xffa07a00u
#define COLORHEX_LIGHTSEAGREEN        0x20b2aa00u
#define COLORHEX_LIGHTSKYBLUE         0x87cefa00u
#define COLORHEX_LIGHTSLATEGRAY       0x77889900u
#define COLORHEX_LIGHTSLATEGREY       0x77889900u
#define COLORHEX_LIGHTSTEELBLUE       0xb0c4de00u
#define COLORHEX_LIGHTYELLOW          0xffffe000u
#define COLORHEX_LIME                 0x00ff0000u
#define COLORHEX_LIMEGREEN            0x32cd3200u
#define COLORHEX_LINEN                0xfaf0e600u
#define COLORHEX_MAGENTA              0xff00ff00u
#define COLORHEX_MAROON               0x80000000u
#define COLORHEX_MEDIUMAQUAMARINE     0x66cdaa00u
#define COLORHEX_MEDIUMBLUE           0x0000cd00u
#define COLORHEX_MEDIUMORCHID         0xba55d300u
#define COLORHEX_MEDIUMPURPLE         0x9370db00u
#define COLORHEX_MEDIUMSEAGREEN       0x3cb37100u
#define COLORHEX_MEDIUMSLATEBLUE      0x7b68ee00u
#define COLORHEX_MEDIUMSPRINGGREEN    0x00fa9a00u
#define COLORHEX_MEDIUMTURQUOISE      0x48d1cc00u
#define COLORHEX_MEDIUMVIOLETRED      0xc7158500u
#define COLORHEX_MIDNIGHTBLUE         0x19197000u
#define COLORHEX_MINTCREAM            0xf5fffa00u
#define COLORHEX_MISTYROSE            0xffe4e100u
#define COLORHEX_MOCCASIN             0xffe4b500u
#define COLORHEX_NAVAJOWHITE          0xffdead00u
#define COLORHEX_NAVY                 0x00008000u
#define COLORHEX_OLDLACE              0xfdf5e600u
#define COLORHEX_OLIVE                0x80800000u
#define COLORHEX_OLIVEDRAB            0x6b8e2300u
#define COLORHEX_ORANGE               0xffa50000u
#define COLORHEX_ORANGERED            0xff450000u
#define COLORHEX_ORCHID               0xda70d600u
#define COLORHEX_PALEGOLDENROD        0xeee8aa00u
#define COLORHEX_PALEGREEN            0x98fb9800u
#define COLORHEX_PALETURQUOISE        0xafeeee00u
#define COLORHEX_PALEVIOLETRED        0xdb709300u
#define COLORHEX_PAPAYAWHIP           0xffefd500u
#define COLORHEX_PEACHPUFF            0xffdab900u
#define COLORHEX_PERU                 0xcd853f00u
#define COLORHEX_PINK                 0xffc0cb00u
#define COLORHEX_PLUM                 0xdda0dd00u
#define COLORHEX_POWDERBLUE           0xb0e0e600u
#define COLORHEX_PURPLE               0x80008000u
#define COLORHEX_REBECCAPURPLE        0x66339900u
#define COLORHEX_RED                  0xff000000u
#define COLORHEX_ROSYBROWN            0xbc8f8f00u
#define COLORHEX_ROYALBLUE            0x4169e100u
#define COLORHEX_SADDLEBROWN          0x8b451300u
#define COLORHEX_SALMON               0xfa807200u
#define COLORHEX_SANDYBROWN           0xf4a46000u
#define COLORHEX_SEAGREEN             0x2e8b5700u
#define COLORHEX_SEASHELL             0xfff5ee00u
#define COLORHEX_SIENNA               0xa0522d00u
#define COLORHEX_SILVER               0xc0c0c000u
#define COLORHEX_SKYBLUE              0x87ceeb00u
#define COLORHEX_SLATEBLUE            0x6a5acd00u
#define COLORHEX_SLATEGRAY            0x70809000u
#define COLORHEX_SLATEGREY            0x70809000u
#define COLORHEX_SNOW                 0xfffafa00u
#define COLORHEX_SPRINGGREEN          0x00ff7f00u
#define COLORHEX_STEELBLUE            0x4682b400u
#define COLORHEX_TAN                  0xd2b48c00u
#define COLORHEX_TEAL                 0x00808000u
#define COLORHEX_THISTLE              0xd8bfd800u
#define COLORHEX_TOMATO               0xff634700u
#define COLORHEX_TURQUOISE            0x40e0d000u
#define COLORHEX_VIOLET               0xee82ee00u
#define COLORHEX_WHEAT                0xf5deb300u
#define COLORHEX_WHITE                0xffffff00u
#define COLORHEX_WHITESMOKE           0xf5f5f500u
#define COLORHEX_YELLOW               0xffff0000u
#define COLORHEX_YELLOWGREEN          0x9acd3200u

#endif //COPYWRITE_COLORS_DEFS_HPP
